title: Daniel Corrieri
description: Game Programmer
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
highlight: rouge

# Collections
collections:
  projects:
    order:
      - STEAMRUSH.md
      - MinimapMaker.md
      - RayTracer.md
      - Snake.md
    output: true

# Site Info
info:
  resume-link: https://drive.google.com/uc?export=download&id=1OkU3IKue2gK4Pf6VL7tSzkp9QVLpWm0U
  linkedin-link: https://www.linkedin.com/in/daniel-corrieri
  gmail-link: mailto:danielcorrieri@gmail.com
  github-link: https://github.com/daxpress
  discord-link: https://discordapp.com/users/380084195210297354